from JodelBot import JodelBot
jbot = JodelBot()
#jbot.scanTopPost(400)
#jbot.getBestImage().show()
#print(jbot.getTopPost("Bremen"))
#jbot.getImage("beufheufgeufheufheufheufheufheufhwuefhwuehfuwefhwuefhwu",500,"bejfwejfbwejfbwejfbwef","FF0000")[0].show()
#jbot.scanTopPost(400)
#print(jbot.j.get_posts_popular(skip=0, limit=10, after=None, mine=False, hashtag=None, channel=None))
jbot.scanTopPost(400)
jbot.getBestImage()[0].show()
jbot.getBestImage()[0].show()
